spring:
  datasource:
    url: jdbc:mysql://10.10.10.102:3306/gorany?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: casper
    password: 12345678
   
   
  thymeleaf:
    cache: false
   